### ISSUE TITLE
Contact Form Not Functioning on Stagging

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#1]
Short code requires some troubleshooting. Make sure the plugin is enabled on the staging site. 

Here is a picture of the issue:
![screen shot 2017-09-14 at 9 47 51 am](https://user-images.githubusercontent.com/5028555/30442671-f1c2439a-9931-11e7-931a-7f31caa3c02a.png)

**Comment by DHilscher** [comment]
odd it is working fine on staging site for me.

**Comment by rcass** [comment]
Hmmm maybe it was all me then! I think it resolved it self in a refresh or something, because I am seeing it now!
