### ISSUE TITLE
jQuery IIFE statement and document.ready consistency in JS files

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#13]
Looking at the JS files, the subscribe-toggle.js doesn't seem to be following the same format as the other JS files.

The other files (that are using jQuery), have wrapped everything in a anonymous function (IIFE statement) then used document.ready then inside as necessary.

Where the subscribe-toggle.js does all of it one line. That is not wrong, but you just want to make sure there is consistency between files.  

I recommend formatting subscribe-toggle.js like the other files.

Here is [resource](https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/) explain this in more detail as well!

**Comment by DHilscher** [comment]
Thanks Rose. That makes sense. I am not sure we will end up using that toggle yet it is currently a placeholder
