### ISSUE TITLE
Make Speaker Page Dynamic 

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#14]
Basically the same issue as the about page. 😢 

The content on the about page should be editable by the user.  Meaning that when the client navigates to the Speaker page in the back end of WordPress, they should see the content (the paragraphs displayed on the page) and be able to edit that content.

TO DO:
- [x] Remove all content from the speaker.php file (all the p & br tags)
- [x] Add or create fields or use the default WYSIWYG, so that About page content can be entered through the WordPress admin area.
- [x] Remove video links in the speaker.php
- [x] Add videos through the WordPress admin area. (Add or create fields or use the default WYSIWYG)

**Comment by DHilscher** [comment]
Done. Thanks Rose!
