### ISSUE TITLE
Font Value Formating

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#15]
All the values for the font family can just be on one line.
![screen shot 2017-09-14 at 1 39 54 pm](https://user-images.githubusercontent.com/5028555/30454767-506c53d4-9952-11e7-9f14-ce9dad2714d8.png)

- [x] Change font__code and font__pre formatting.

- [x] Add fall back fonts to font__main. Also is your main font really just sans-serif??

**Comment by mariesarabia** [comment]
Neglected to remove duplicate/default font__main (sans-serif); removed now. 
Turned off VS Code formatter extension which was autoformatting font values as separate lines.
Added fall back fonts to existing Roboto font.
