### ISSUE TITLE
Make front-page.php content more dynamic

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#19]
For the front-page.php, all of the content seems to be added via just hard coding in.
This is really not the best solution, because most clients will want access to change this content.

Try removing as much of this content from the front-page.php and have it dynamically accessible through the WordPress Admin area. (basically you should not have paragraphs of content saved in your theme at all)

**Comment by DHilscher** [comment]
Made all the content dynamic. Thanks Rose!
