### ISSUE TITLE
Update functionality plugin name and placeholders

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#3]
There are a few place holders in the functionality that need to be changed.

- [x] remove the placeholder from the functionality plugin name (aka remove [site name] )

![screen shot 2017-09-14 at 9 58 00 am](https://user-images.githubusercontent.com/5028555/30443120-57601d2a-9933-11e7-8a4f-adbde88c0cfa.png)

- [x] change the copyright details (aka the year and name) in red-functionality.php

- [x] change php file from red-functionality to danielfox-functionality or fox-functionality (something like that)

- [x] There are two READMEs at the moment (readme.txt or README.md), please delete the one you don't need.

**Comment by DHilscher** [comment]
fixed these. Thanks Rose!
