### ISSUE TITLE
Make About Page Content Dynamic

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#5]
The content on the about page should be editable by the user.  Meaning that when the client navigates to the About page in the back end of WordPress, they should see the content (the paragraphs displayed on the page) and be able to edit that content.

Currently, the about.php, has some content saved right into the template file 😱 
This is a no-no because:
- The client need to edit this content
- This content will probably change
- You shouldn't need a developer every time you need to make a content change.

Also, you need to assume the images will want to be changed by the client in the future, therefore the client should have the ability to change the images on the page through the WordPress Admin area (on the about page).

TO DO:
- [x] Remove all content from the about.php file (all the p tags)
- [x] Add or create fields or use the default WYSIWYG, so that About page content can be entered through the WordPress admin area.
- [x] Remove specific image called on the about.php
- [x] Add images through the WordPress admin area. (Add or create fields or use the default WYSIWYG)

**Comment by DHilscher** [comment]
finished. Thanks Rose!

**Comment by rcass** [comment]
Nice! This is a step in the right direction. 

My only thought is for the text perhaps using a WYSIWYG so the client would have an easier time editing, since it is a fair bit of content
