### ISSUE TITLE
Social Media SVG, Could we just use Font Awesome?

### ISSUE THREAD

**Issue by rcass** [redacademy/fox-summer-2017#9]
I noticed in the assets folder there are two svgs, that I think rather than used seperate SVGs and have those files saved in the theme, you should just use font awesome and css.

facebook_white and instrgram_white look like they both can use the font awesome version and then just apply css (add padding, then a background color, then a border radius, volia!)

**Comment by mariesarabia** [comment]
Added font awesome icons and applied CSS styling to achieve appearance of original svg icons. But might need to replace these with built-in icons from jsSocials if that jQuery plugin will be used for post sharing function.

**Comment by mariesarabia** [comment]
Designers want to use the svg icons they provided for social media and navigation and will need to see how to integrate that with a social media sharing plugin

**Comment by mariesarabia** [comment]
Got the jsSocials plugin icons displaying on the page (currently using jssocials default fontawesome icons and not the designers' own svgs)

**Comment by rcass** [comment]
Sounds good to me! is this complete? I noticed you reopened it

**Comment by mariesarabia** [comment]
Tried to see if I can get the custom logos to work on jsSocials but determined that it is best to keep the default font-awesome since it's already working and look very similar to the designers' icons. This should be a closed issue now. Thanks Rose!
